name       : md4c
version    : 0.4.8
release    : 1
source     :
    - https://github.com/mity/md4c/archive/refs/tags/release-0.4.8.tar.gz : 4a457df853425b6bb6e3457aa1d1a13bccec587a04c38c622b1013a0da41439f
license    : MIT
component  : programming.library
summary    : C Markdown parser and library
description: |
    C Markdown parser. Fast. SAX-like interface. Compliant to CommonMark specification.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
